version: 2

project_name: obs-exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: obs-exporter
    binary: obs-exporter
    main: ./cmd/obs-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .FullCommit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}

archives:
  - id: obs-exporter
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: miyamadoKL
    name: prometheus-obs-exporter
